### ISSUE TITLE
Setup external LIDAR rig

### ISSUE THREAD

**Issue by asorici** [ami-lab/sparc#5]
### Why
Pepper's own sensors and odometry are not capable of providing an accurate localization within a known map. We need to rely on the more powerful external LIDAR to perform this.

### What
  - build physical rig to attach exernal LIDAR  and RaspberryPI to Pepper robot
  - implement LIDAR measurement collection on RaspberryPI
  - define geometric transformation of LIDAR rig with respect to Pepper base_frame

### Done Condition
  - LIDAR messages are viewable on laptop running ROS core
  - ROS transformation tree listing displays LIDAR position with respect to Pepper robot

**Comment by alexandrugavril** [comment]
I've managed to attach the LIDAR to the Robot. 
We are still blocked by the fact that the battery pack I have is insufficient to power up the Robot. I will buy a new power bank and finish the task.
